"""Unit tests for report rendering."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pytest

from review_pulse.config import load_config
from review_pulse.models import ReportDraft, ReportTheme, ReportQuote
from review_pulse.render.markdown import render_markdown_report


@pytest.fixture
def dummy_draft() -> ReportDraft:
    return ReportDraft(
        summary="Overall positive sentiment regarding the new stock search improvements, but some complaints about mutual fund transaction performance.",
        themes=[
            ReportTheme(
                label="Stock Search UI",
                description="Users praise the faster stock lookup UI.",
                review_count=60,
                avg_rating=4.5,
            ),
            ReportTheme(
                label="Mutual Fund Redeem",
                description="Redemption speed remains sluggish.",
                review_count=40,
                avg_rating=2.5,
            ),
        ],
        quotes=[
            ReportQuote(
                text="Stock lookup UI is extremely fast now!",
                rating=5,
                source="google_play",
                review_date=date(2026, 4, 1),
                theme_label="Stock Search UI",
            ),
            ReportQuote(
                text="Redemption takes forever, please optimize.",
                rating=2,
                source="app_store",
                review_date=date(2026, 4, 2),
                theme_label="Mutual Fund Redeem",
            ),
        ],
        action_ideas=[
            "Optimize the mutual fund redemption API latency.",
            "Continue rolling out the stock search layout.",
        ],
    )


def test_markdown_rendering(dummy_draft, tmp_path) -> None:
    config = load_config("indmoney")
    output_dir = tmp_path / "reports"

    rendered = render_markdown_report(
        draft=dummy_draft,
        product_slug="indmoney",
        product_display_name="INDMoney",
        week_start=date(2026, 3, 30),
        week_end=date(2026, 4, 5),
        reviews_count=100,
        run_id="mock_run_id",
        config=config,
        output_dir=output_dir,
    )

    # 1. Verify file exists
    report_file = output_dir / "indmoney-2026-03-30.md"
    assert report_file.exists()

    # 2. Check sections are present
    content = report_file.read_text(encoding="utf-8")
    assert "# INDMoney — Weekly Review Pulse" in content
    assert "**Reporting Week:** March 30, 2026 – April 05, 2026" in content
    assert "**Reviews Analyzed:** 100" in content
    assert "## Executive Summary" in content
    assert "## Top Themes" in content
    assert "1. **Stock Search UI** — Users praise the faster stock lookup UI. (60 reviews, avg ★4.5)" in content
    assert "## Representative Quotes" in content
    assert '> "Stock lookup UI is extremely fast now!" — 5★, Google Play, 2026-04-01' in content
    assert '> "Redemption takes forever, please optimize." — 2★, App Store, 2026-04-02' in content
    assert "## Action Ideas" in content
    assert "- Optimize the mutual fund redemption API latency." in content
    assert "_Generated by Review Pulse · Run ID: mock_run_id_" in content


def test_markdown_rendering_limits(dummy_draft, tmp_path) -> None:
    config = load_config("indmoney")
    # Set tight limits in config override
    config.report.max_themes = 1
    config.report.max_action_ideas = 1
    config.report.max_quotes_per_theme = 0  # no quotes

    output_dir = tmp_path / "reports"

    rendered = render_markdown_report(
        draft=dummy_draft,
        product_slug="indmoney",
        product_display_name="INDMoney",
        week_start=date(2026, 3, 30),
        week_end=date(2026, 4, 5),
        reviews_count=100,
        run_id="mock_run_id",
        config=config,
        output_dir=output_dir,
    )

    # Check limits are enforced
    assert "Stock Search UI" in rendered
    assert "Mutual Fund Redeem" not in rendered  # limit to 1 theme
    assert "- Optimize the mutual fund redemption" in rendered
    assert "- Continue rolling out" not in rendered  # limit to 1 action idea
    assert ">" not in rendered  # no quotes printed
